# Generated by Django 3.2.8 on 2021-10-23 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='englishword',
            options={'verbose_name': 'english_word', 'verbose_name_plural': 'english_words'},
        ),
        migrations.AlterModelOptions(
            name='koreanword',
            options={'verbose_name': 'korean_word', 'verbose_name_plural': 'korean_words'},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'verbose_name': 'word', 'verbose_name_plural': 'words'},
        ),
    ]
