# Generated by Django 3.2.8 on 2021-10-24 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_auto_20211023_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='englishword',
            options={'managed': True, 'verbose_name': 'EnglishWord', 'verbose_name_plural': 'EnglishWords'},
        ),
        migrations.AlterModelOptions(
            name='koreanword',
            options={'managed': True, 'verbose_name': 'KoreanWord', 'verbose_name_plural': 'KoreanWords'},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'managed': True, 'verbose_name': 'word', 'verbose_name_plural': 'words'},
        ),
        migrations.AlterModelTable(
            name='englishword',
            table='english_words',
        ),
        migrations.AlterModelTable(
            name='koreanword',
            table='korean_words',
        ),
        migrations.AlterModelTable(
            name='word',
            table='words',
        ),
    ]
