# Generated by Django 3.2.8 on 2021-10-24 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0003_auto_20211024_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'managed': True, 'verbose_name': 'Word', 'verbose_name_plural': 'Words'},
        ),
    ]
