# Generated by Django 3.2.8 on 2021-10-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0004_alter_word_options'),
        ('word_group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordgroup',
            name='words',
            field=models.ManyToManyField(related_name='words', to='word.Word'),
        ),
    ]
