# Generated by Django 3.2.8 on 2021-10-23 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_username_user_nickname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
